// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "4398c316512792e2470db58e4905f24f69063a80b26d6b79f22113b76163147b")
