// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "6b8ff762fd21fa2e591dc525a2a17353b7880ef24a8017c38c65e8fe168e5caf")
